# Generated by Django 4.1.5 on 2023-02-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('banner_url', models.CharField(max_length=100, verbose_name='Emlace')),
                ('publication', models.BooleanField(default=True)),
                ('img_url', models.CharField(max_length=100, verbose_name='Imagen')),
                ('fiel', models.FileField(blank=True, null=True, upload_to='archivo/%y/%m/%d')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
