# Generated by Django 4.1.5 on 2023-02-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_url',
            field=models.CharField(max_length=100, verbose_name='Enlace'),
        ),
    ]
