# Generated by Django 4.1.5 on 2023-02-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_alter_banner_banner_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesOfInyerest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.CharField(max_length=100, verbose_name='Logotipo')),
                ('sito_web', models.CharField(max_length=100, verbose_name='Link')),
                ('decription', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'places_of_inyerest',
                'verbose_name_plural': 'places_of_inyerest',
                'db_table': 'places_of_inyerest',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-id'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banners',
        ),
    ]
