# Generated by Django 4.1.5 on 2023-02-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_placesofinyerest_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlacesOfInyerest',
            new_name='PlacesOfInterest',
        ),
        migrations.AlterModelOptions(
            name='placesofinterest',
            options={'ordering': ['-id'], 'verbose_name': 'places_of_interest', 'verbose_name_plural': 'places_of_interest'},
        ),
        migrations.AlterModelTable(
            name='placesofinterest',
            table='places_of_interest',
        ),
    ]
