# Generated by Django 4.1.5 on 2023-06-29 03:25

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarometroTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePDF', models.CharField(blank=True, max_length=100, null=True)),
                ('yearPDF', models.IntegerField(null=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('doc', models.FileField(blank=True, storage=web.models.S3Storage(), upload_to='barometro-turistico', verbose_name='Documento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('enero_data', models.IntegerField(blank=True, null=True)),
                ('febrero_data', models.IntegerField(blank=True, null=True)),
                ('marzo_data', models.IntegerField(blank=True, null=True)),
                ('abril_data', models.IntegerField(blank=True, null=True)),
                ('mayo_data', models.IntegerField(blank=True, null=True)),
                ('junio_data', models.IntegerField(blank=True, null=True)),
                ('julio_data', models.IntegerField(blank=True, null=True)),
                ('agosto_data', models.IntegerField(blank=True, null=True)),
                ('septiembre_data', models.IntegerField(blank=True, null=True)),
                ('octubre_data', models.IntegerField(blank=True, null=True)),
                ('noviembre_data', models.IntegerField(blank=True, null=True)),
                ('diciembre_data', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilVisistantePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.IntegerField(null=True)),
                ('subseccion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrePDF', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('yearPDF', models.IntegerField(null=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
