# Generated by Django 4.1.5 on 2023-02-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarometroTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(null=True)),
                ('nombrePDF', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('yearPDF', models.IntegerField(null=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
