# Generated by Django 4.1.5 on 2023-06-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('seccion', models.IntegerField(null=True)),
            ],
        ),
    ]
