# Generated by Django 4.1.5 on 2023-02-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilvisistantepdf',
            old_name='nombre',
            new_name='nombrePDF',
        ),
        migrations.AddField(
            model_name='perfilvisistantepdf',
            name='puebloMagico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
