# Generated by Django 4.1.5 on 2023-02-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_nombre_perfilvisistantepdf_nombrepdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilvisistantepdf',
            name='yearPDF',
            field=models.IntegerField(null=True),
        ),
    ]
