# Generated by Django 4.1.5 on 2023-05-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_encuesta2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encuesta',
        ),
    ]
