# Generated by Django 4.1.5 on 2023-02-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_barometroturistico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilvisistantepdf',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
