# Generated by Django 4.1.5 on 2023-05-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_encuesta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Encuesta2',
            new_name='Encuesta',
        ),
    ]
