# Generated by Django 4.1.5 on 2023-02-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_perfilvisistantepdf_yearpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilvisistantepdf',
            name='descargas',
            field=models.IntegerField(null=True),
        ),
    ]
