# Generated by Django 4.1.5 on 2023-02-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_perfilvisistantepdf_descargas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilvisistantepdf',
            old_name='descargas',
            new_name='num_descargas',
        ),
    ]
