# Generated by Django 4.1.5 on 2023-06-22 16:18

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_encuesta2_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barometroturistico',
            name='url',
            field=models.FileField(blank=True, null=True, storage=web.models.S3Storage(), upload_to='barometro'),
        ),
    ]
