# Generated by Django 4.1.5 on 2023-02-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_descargas_perfilvisistantepdf_num_descargas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilvisistantepdf',
            name='num_descargas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
