# Generated by Django 4.1.5 on 2023-03-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_datapoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='date',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='value',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='año',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
