# Generated by Django 4.1.5 on 2023-06-22 16:43

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_barometroturistico_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barometroturistico',
            name='url',
            field=models.FileField(storage=web.models.S3Storage(), upload_to='barometro', verbose_name='Archivo'),
        ),
    ]
