# Generated by Django 4.1.5 on 2023-02-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_perfilvisistantepdf_num_descargas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilvisistantepdf',
            name='seccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
