# Generated by Django 4.1.5 on 2023-03-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_datapoint_date_remove_datapoint_option1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='año',
            new_name='year',
        ),
    ]
