# Generated by Django 4.1.5 on 2023-06-22 17:04

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_barometroturistico_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barometroturistico',
            name='url',
        ),
        migrations.AddField(
            model_name='barometroturistico',
            name='doc',
            field=models.FileField(blank=True, storage=web.models.S3Storage(), upload_to='barometro-turistico', verbose_name='Archivo'),
        ),
    ]
