# Generated by Django 4.1.5 on 2023-03-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_año_datapoint_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='mes',
            field=models.IntegerField(null=True),
        ),
    ]
