# Generated by Django 4.1.5 on 2023-06-28 14:31

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_barometroturistico_url_barometroturistico_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barometroturistico',
            name='semestre',
        ),
        migrations.AlterField(
            model_name='barometroturistico',
            name='doc',
            field=models.FileField(blank=True, storage=web.models.S3Storage(), upload_to='barometro-turistico', verbose_name='Documento'),
        ),
    ]
