# Generated by Django 4.1.5 on 2023-02-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_perfilvisistantepdf_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilvisistantepdf',
            name='seccion',
        ),
    ]
