# Generated by Django 4.1.5 on 2023-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_datapoint_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='mes',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='abril',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='agosto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='diciembre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='enero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='febrero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='julio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='junio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='marzo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='mayo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='noviembre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='octubre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='septiembre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
