# Generated by Django 4.1.5 on 2023-02-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_perfilvisistantepdf_seccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilvisistantepdf',
            old_name='puebloMagico',
            new_name='seccion',
        ),
        migrations.AddField(
            model_name='perfilvisistantepdf',
            name='subseccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
