# Generated by Django 4.1.5 on 2023-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_pueblomagico_perfilvisistantepdf_seccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilvisistantepdf',
            name='seccion',
            field=models.IntegerField(null=True),
        ),
    ]
