# Generated by Django 4.1.5 on 2023-03-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_datapoint_mes_datapoint_abril_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='abril',
            new_name='abril_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='agosto',
            new_name='agosto_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='diciembre',
            new_name='diciembre_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='enero',
            new_name='enero_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='data',
            new_name='estado_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='febrero',
            new_name='febrero_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='julio',
            new_name='julio_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='junio',
            new_name='junio_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='marzo',
            new_name='marzo_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='mayo',
            new_name='mayo_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='noviembre',
            new_name='noviembre_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='octubre',
            new_name='octubre_data',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='septiembre',
            new_name='septiembre_data',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='estado',
        ),
    ]
