# Generated by Django 4.1.5 on 2023-03-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_abril_datapoint_abril_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='estado_data',
            new_name='estado',
        ),
    ]
