# Generated by Django 4.1.5 on 2023-03-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_encuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosario',
            name='fecha_registro',
        ),
    ]
