# Generated by Django 4.1.5 on 2023-03-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_glosario_fecha_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glosario',
        ),
    ]
