# Generated by Django 4.1.5 on 2023-05-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
