# Generated by Django 4.1.5 on 2023-07-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0003_alter_profile_facebook_alter_profile_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
