# Generated by Django 4.1.5 on 2023-04-26 15:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='pdf/')),
                ('visible', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'alba',
                'verbose_name_plural': 'alba',
                'db_table': 'alba',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('banner_url', models.CharField(max_length=100, verbose_name='Enlace')),
                ('publication', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CalidadAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('municipio', models.CharField(max_length=555)),
                ('calidad_del_aire', models.CharField(max_length=2255)),
            ],
            options={
                'verbose_name': 'aire',
                'verbose_name_plural': 'aire',
                'db_table': 'aire',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CatalagoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalagoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=455)),
                ('entidad', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='catalogo_categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='catalogo_destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='catalogo_zonaz_arq_museos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museo_zona_arqueologica', models.CharField(max_length=455)),
                ('tipo', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField()),
                ('publicacion', models.BooleanField(blank=True, default=False, null=True)),
                ('visible', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('cuartos_registrados', models.IntegerField()),
                ('cuartos_disponibles', models.IntegerField()),
                ('cuartos_disponibles_prom', models.IntegerField()),
                ('cuartos_ocupados', models.IntegerField()),
                ('cuartos_ocupados_residentes', models.IntegerField()),
                ('cuartos_ocupados_no_residentes', models.IntegerField()),
                ('llegadas_turistas', models.IntegerField()),
                ('llegadas_turistas_residentes', models.IntegerField()),
                ('llegadas_turistas_no_residentes', models.IntegerField()),
                ('turistas_noche', models.IntegerField()),
                ('turistas_noche_residentes', models.IntegerField()),
                ('turistas_noche_no_residentes', models.IntegerField()),
                ('porcentaje_ocupacion', models.FloatField()),
                ('porcentaje_ocupacion_residentes', models.FloatField()),
                ('porcentaje_ocupacion_no_residentes', models.FloatField()),
                ('estadia_promedio', models.FloatField()),
                ('estadia_promedio_residentes', models.FloatField()),
                ('estadia_promedio_no_residentes', models.FloatField()),
                ('densidad_ocupacion', models.FloatField()),
                ('densidad_ocupacion_residentes', models.FloatField()),
                ('densidad_ocupacion_no_residentes', models.FloatField()),
                ('fecha_recuperacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_evento', models.TextField()),
                ('tipo_evento1', models.TextField()),
                ('imagen', models.ImageField(upload_to='images/')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoDerrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('categoria', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('gasto_diario_promedio', models.FloatField()),
                ('participacion', models.FloatField()),
                ('estadia_promedio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(blank=True, max_length=100, null=True)),
                ('definicion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioHotelero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=255)),
                ('habitaciones', models.IntegerField()),
                ('establecimientos', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inventario_hotelero_gto',
                'verbose_name_plural': 'inventario_hotelero_gto',
                'db_table': 'inventario_hotelero_gto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioHoteleroEntNac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=255)),
                ('habitaciones', models.IntegerField()),
                ('establecimientos', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inventario_hotelero_ent_nac',
                'verbose_name_plural': 'inventario_hotelero_ent_nac',
                'db_table': 'inventario_hotelero_ent_nac',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InversionPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('municipio', models.CharField(max_length=255)),
                ('nombre_obra', models.CharField(max_length=255)),
                ('monto_inversion_municipal', models.FloatField()),
                ('monto_inversion_estatal', models.FloatField()),
                ('monto_inversion_federal', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Inversiones Públicas',
                'db_table': 'inversion_publica',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('sitio_web', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fecha_nota', models.DateField()),
                ('autor_foto', models.CharField(max_length=100)),
                ('autor_nota', models.CharField(max_length=100)),
                ('fecha_recuperacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='otros_anuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('pib_total_sector_72', models.FloatField()),
                ('pib_total_de_actividades_terciarias', models.FloatField()),
                ('basura_generada_por_persona_diaria', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacesOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.CharField(max_length=100, verbose_name='Logotipo')),
                ('sitio_web', models.URLField(verbose_name='Link')),
                ('decription', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'places_of_interest',
                'verbose_name_plural': 'places_of_interest',
                'db_table': 'places_of_interest',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionesCentroDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='zonas_arqueologicas_museos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('museo_zona_arqueologica', models.CharField(max_length=455)),
                ('fecha', models.DateField()),
                ('origen_visitante', models.CharField(max_length=455)),
                ('visitantes', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=455, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('recent', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('1', 'PDF'), ('2', 'MP3'), ('3', 'XLS')], max_length=10)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.categorias')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.seccionescentrodocumental')),
            ],
        ),
        migrations.AddField(
            model_name='categorias',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.seccionescentrodocumental'),
        ),
    ]
