# Generated by Django 4.1.5 on 2023-08-17 18:36

import back.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='pdf/')),
                ('visible', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'alba',
                'verbose_name_plural': 'alba',
                'db_table': 'alba',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('banner_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace')),
                ('imagen', models.ImageField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='banner-images')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo')),
                ('titulo_pricipal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo Principal')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Eniot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePDF', models.CharField(blank=True, max_length=100, null=True)),
                ('seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('anio', models.IntegerField(null=True)),
                ('doc_url', models.FileField(storage=back.models.S3Storage(), upload_to='eniot', verbose_name='Documento')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EniotAlbun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlbun', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_url', models.FileField(storage=back.models.S3Storage(), upload_to='eniot', verbose_name='Documento')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_evento', models.TextField()),
                ('imagen', models.ImageField(storage=back.models.S3Storage(), upload_to='oteg')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(blank=True, max_length=300, null=True)),
                ('definicion', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('tipo_de_visitante', models.CharField(blank=True, max_length=455, null=True)),
                ('gasto_diario_promedio', models.FloatField()),
                ('participacion', models.FloatField()),
                ('estadia_promedio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('sitio_web', models.URLField()),
                ('fecha_nota', models.DateField()),
                ('autor_foto', models.CharField(max_length=100)),
                ('autor_nota', models.CharField(max_length=100)),
                ('fecha_recuperacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='noticias')),
            ],
        ),
        migrations.CreateModel(
            name='PlacesOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(storage=back.models.S3Storage(), upload_to='logos', verbose_name='Logotipo')),
                ('sitio_web', models.URLField(verbose_name='Link')),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'places_of_interest',
                'verbose_name_plural': 'places_of_interest',
                'db_table': 'places_of_interest',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('nomenclatura', models.CharField(blank=True, max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('iframe', models.TextField()),
                ('dimension', models.CharField(blank=True, max_length=100)),
                ('ods1', models.BooleanField(default=False)),
                ('ods2', models.BooleanField(default=False)),
                ('ods3', models.BooleanField(default=False)),
                ('ods4', models.BooleanField(default=False)),
                ('ods5', models.BooleanField(default=False)),
                ('ods6', models.BooleanField(default=False)),
                ('ods7', models.BooleanField(default=False)),
                ('ods8', models.BooleanField(default=False)),
                ('ods9', models.BooleanField(default=False)),
                ('ods10', models.BooleanField(default=False)),
                ('ods11', models.BooleanField(default=False)),
                ('ods12', models.BooleanField(default=False)),
                ('ods13', models.BooleanField(default=False)),
                ('ods14', models.BooleanField(default=False)),
                ('ods15', models.BooleanField(default=False)),
                ('ods16', models.BooleanField(default=False)),
                ('ods17', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes_Mensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, max_length=100)),
                ('ano', models.CharField(blank=True, max_length=100)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('doc', models.FileField(blank=True, storage=back.models.S3Storage(), upload_to='reportes_mensuales', verbose_name='Documento')),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeccionesCentroDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='secciones')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('1', 'PDF'), ('2', 'MP3'), ('3', 'XLS')], max_length=10, verbose_name='Tipo de Documento')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('doc', models.FileField(storage=back.models.S3Storage(), upload_to='publications', verbose_name='Documento')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.categorias')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.seccionescentrodocumental')),
            ],
        ),
        migrations.AddField(
            model_name='categorias',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.seccionescentrodocumental'),
        ),
    ]
