# Generated by Django 4.1.5 on 2023-05-16 23:12

import back.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='pdf/')),
                ('visible', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'alba',
                'verbose_name_plural': 'alba',
                'db_table': 'alba',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('banner_url', models.CharField(max_length=100, verbose_name='Enlace')),
                ('publication', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='banner-images')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField()),
                ('publicacion', models.BooleanField(blank=True, default=False, null=True)),
                ('visible', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('tipo_de_certificacion', models.CharField(max_length=455)),
                ('empresas_certificadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=256, null=True)),
                ('categoria', models.CharField(max_length=256, null=True)),
                ('fecha', models.DateField(null=True)),
                ('cuartos_registrados_fin_periodo', models.FloatField(null=True)),
                ('cuartos_disponibles_promedio', models.FloatField(null=True)),
                ('cuartos_disponibles', models.FloatField(null=True)),
                ('cuartos_ocupados', models.FloatField(null=True)),
                ('cuartos_ocupados_residentes', models.FloatField(null=True)),
                ('cuartos_ocupados_no_residentes', models.FloatField(null=True)),
                ('llegadas_de_turistas', models.FloatField(null=True)),
                ('llegadas_de_turistas_residentes', models.FloatField(null=True)),
                ('llegadas_de_turistas_no_residentes', models.FloatField(null=True)),
                ('turistas_noche', models.FloatField(null=True)),
                ('turistas_noche_residentes', models.FloatField(null=True)),
                ('turistas_noche_no_residentes', models.FloatField(null=True)),
                ('porcentaje_de_ocupacion', models.FloatField(null=True)),
                ('porcentaje_de_ocupacion_residentes', models.FloatField(null=True)),
                ('porcentaje_de_ocupacion_no_residentes', models.FloatField(null=True)),
                ('estadia_promedio', models.FloatField(null=True)),
                ('estadia_promedio_residentes', models.FloatField(null=True)),
                ('estadia_promedio_no_residentes', models.FloatField(null=True)),
                ('densidad_de_ocupacion', models.FloatField(null=True)),
                ('densidad_de_ocupacion_residentes', models.FloatField(null=True)),
                ('densidad_de_ocupacion_no_residentes', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_evento', models.TextField()),
                ('imagen', models.ImageField(storage=back.models.S3Storage(), upload_to='eventos')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoDerrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('categoria', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('gasto_diario_promedio', models.FloatField()),
                ('participacion', models.FloatField()),
                ('estadia_promedio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(blank=True, max_length=100, null=True)),
                ('definicion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inversion_privada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_del_proyecto', models.CharField(max_length=455)),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('fecha', models.DateField()),
                ('monto_ejecutado', models.FloatField()),
                ('avance_proyecto', models.FloatField()),
                ('nombre_del_proyecto', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('sitio_web', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='noticias')),
                ('fecha_nota', models.DateField()),
                ('autor_foto', models.CharField(max_length=100)),
                ('autor_nota', models.CharField(max_length=100)),
                ('fecha_recuperacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='otros_anuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('pib_total_sector_72', models.FloatField()),
                ('pib_total_de_actividades_terciarias', models.FloatField()),
                ('basura_generada_por_persona_diaria', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacesOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(storage=back.models.S3Storage(), upload_to='logos', verbose_name='Logotipo')),
                ('sitio_web', models.URLField(verbose_name='Link')),
                ('decription', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'places_of_interest',
                'verbose_name_plural': 'places_of_interest',
                'db_table': 'places_of_interest',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionesCentroDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sesibilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('participantes', models.IntegerField()),
                ('accion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('recent', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('1', 'PDF'), ('2', 'MP3'), ('3', 'XLS')], max_length=10)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.categorias')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.seccionescentrodocumental')),
            ],
        ),
        migrations.AddField(
            model_name='categorias',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.seccionescentrodocumental'),
        ),
    ]
