# Generated by Django 4.1.5 on 2023-05-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hombres_empleados_gto', models.IntegerField(default=None, null=True)),
                ('mujeres_empleadas_gto', models.IntegerField(default=None, null=True)),
                ('hombres_empleados_sec_72_gto', models.IntegerField(default=None, null=True)),
                ('mujeres_empleadas_sec_72_gto', models.IntegerField(default=None, null=True)),
                ('hombres_empleados_sec_72_nac', models.IntegerField(default=None, null=True)),
                ('mujeres_empleadas_sec_72_nac', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
