# Generated by Django 4.1.5 on 2023-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosario',
            name='definicion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='glosario',
            name='palabra',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
