# Generated by Django 4.1.5 on 2023-03-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_evento1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
