# Generated by Django 4.1.5 on 2023-06-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo'),
        ),
        migrations.AddField(
            model_name='banner',
            name='titulo_pricipal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo Principal'),
        ),
    ]
