# Generated by Django 4.1.5 on 2023-02-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesofinterest',
            name='sitio_web',
            field=models.TextField(verbose_name='Link'),
        ),
    ]
