# Generated by Django 4.1.5 on 2023-05-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('tipo_de_certificacion', models.CharField(max_length=455)),
                ('empresas_certificadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='inversion_privada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_del_proyecto', models.CharField(max_length=455)),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('fecha', models.DateField()),
                ('monto_ejecutado', models.FloatField()),
                ('avance_proyecto', models.FloatField()),
                ('nombre_del_proyecto', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='Sesibilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('participantes', models.IntegerField()),
                ('accion', models.IntegerField()),
            ],
        ),

        migrations.RemoveField(
            model_name='datatour',
            name='cuartos_disponibles_prom',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='cuartos_registrados',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='densidad_ocupacion',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='densidad_ocupacion_no_residentes',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='densidad_ocupacion_residentes',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='fecha_recuperacion',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='llegadas_turistas',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='llegadas_turistas_no_residentes',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='llegadas_turistas_residentes',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='porcentaje_ocupacion',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='porcentaje_ocupacion_no_residentes',
        ),
        migrations.RemoveField(
            model_name='datatour',
            name='porcentaje_ocupacion_residentes',
        ),
        migrations.AddField(
            model_name='datatour',
            name='cuartos_disponibles_promedio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='cuartos_registrados_fin_periodo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='densidad_de_ocupacion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='densidad_de_ocupacion_no_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='densidad_de_ocupacion_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='llegadas_de_turistas',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='llegadas_de_turistas_no_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='llegadas_de_turistas_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='porcentaje_de_ocupacion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='porcentaje_de_ocupacion_no_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatour',
            name='porcentaje_de_ocupacion_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='categoria',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='cuartos_disponibles',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='cuartos_ocupados',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='cuartos_ocupados_no_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='cuartos_ocupados_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='destino',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='estadia_promedio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='estadia_promedio_no_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='estadia_promedio_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='turistas_noche',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='turistas_noche_no_residentes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatour',
            name='turistas_noche_residentes',
            field=models.FloatField(null=True),
        ),
    ]
