# Generated by Django 4.1.5 on 2023-05-12 17:14

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesibilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('participantes', models.IntegerField()),
                ('accion', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CalidadAire',
        ),
        migrations.DeleteModel(
            name='CatalagoCategoria',
        ),
        migrations.DeleteModel(
            name='CatalagoDestino',
        ),
        migrations.DeleteModel(
            name='catalogo_categorias',
        ),
        migrations.DeleteModel(
            name='catalogo_destinos',
        ),
        migrations.DeleteModel(
            name='catalogo_zonaz_arq_museos',
        ),
        migrations.DeleteModel(
            name='InventarioHotelero',
        ),
        migrations.DeleteModel(
            name='InventarioHoteleroEntNac',
        ),
        migrations.DeleteModel(
            name='InversionPublica',
        ),
        migrations.DeleteModel(
            name='zonas_arqueologicas_museos',
        ),
        migrations.AlterField(
            model_name='datatour',
            name='destino',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AlterField(
            model_name='placesofinterest',
            name='logotipo',
            field=models.ImageField(storage=back.models.S3Storage(), upload_to='logos', verbose_name='Logotipo'),
        ),
    ]
