# Generated by Django 4.1.5 on 2023-08-17 00:57

import back.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eniot',
            name='doc_url',
            field=models.FileField(storage=back.models.S3Storage(), upload_to='eniot', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='eniotalbun',
            name='foto_url',
            field=models.FileField(storage=back.models.S3Storage(), upload_to='eniot', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='glosario',
            name='definicion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='glosario',
            name='palabra',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.categorias'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='doc',
            field=models.FileField(storage=back.models.S3Storage(), upload_to='publications', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.seccionescentrodocumental'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='type',
            field=models.CharField(choices=[('1', 'PDF'), ('2', 'MP3'), ('3', 'XLS')], max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
