# Generated by Django 4.1.5 on 2023-04-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogo_categorias',
            table='categoriaV2',
        ),
        migrations.AlterModelTable(
            name='publications',
            table='publicationV2',
        ),
    ]
