# Generated by Django 4.1.5 on 2023-08-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='anio',
            field=models.IntegerField(null=True),
        ),
    ]
