# Generated by Django 4.1.5 on 2023-02-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('sitio_web', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fecha_nota', models.DateField()),
                ('autor_foto', models.CharField(max_length=100)),
                ('autor_nota', models.CharField(max_length=100)),
                ('fecha_recuperacion', models.DateField()),
            ],
        ),
    ]
