# Generated by Django 4.1.5 on 2023-05-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_empleo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('destino', models.CharField(blank=True, max_length=455, null=True)),
                ('gasto_diario_promedio', models.FloatField()),
                ('participacion', models.FloatField()),
                ('estadia_promedio', models.FloatField()),
            ],
        ),
    ]
