# Generated by Django 4.1.5 on 2023-06-27 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_banner_subtitulo_banner_titulo_pricipal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='publication',
            new_name='activo',
        ),
    ]
