# Generated by Django 4.1.5 on 2023-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_glosario_definicion_alter_glosario_palabra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='type',
            field=models.CharField(choices=[('1', 'PDF'), ('2', 'MP3'), ('3', 'XLS')], max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
