# Generated by Django 4.1.5 on 2023-05-15 16:38

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_sesibilizacion_delete_calidadaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='banner-images'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(storage=back.models.S3Storage(), upload_to='eventos'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='noticias'),
        ),
    ]
