# Generated by Django 4.1.5 on 2023-04-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_catalogo_categorias_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogo_categorias',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='publications',
            table='publication',
        ),
    ]
