# Generated by Django 4.1.5 on 2023-02-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_placesofinterest_sitio_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesofinterest',
            name='sitio_web',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
