# Generated by Django 4.1.5 on 2023-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_inventariohotelero'),
    ]

    operations = [
        migrations.CreateModel(
            name='InversionPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('municipio', models.CharField(max_length=255)),
                ('nombre_obra', models.CharField(max_length=255)),
                ('monto_inversion_municipal', models.FloatField()),
                ('monto_inversion_estatal', models.FloatField()),
                ('monto_inversion_federal', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Inversiones Públicas',
                'db_table': 'inversion_publica',
                'ordering': ['-id'],
            },
        ),
    ]
