# Generated by Django 4.1.5 on 2023-02-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='pdf/')),
                ('visible', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'alba',
                'verbose_name_plural': 'alba',
                'db_table': 'alba',
                'ordering': ['-id'],
            },
        ),
    ]
