# Generated by Django 4.1.5 on 2023-05-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_modelogd'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelogd',
            name='tipo_de_visitante',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
