# Generated by Django 4.1.5 on 2023-06-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_rename_publication_banner_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enlace'),
        ),
    ]
