# Generated by Django 4.1.5 on 2023-02-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='fiel',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='img_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
