# Generated by Django 4.1.5 on 2023-04-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_catalogo_categorias_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo_categorias',
            options={},
        ),
        migrations.AlterModelTable(
            name='catalogo_categorias',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publications',
            table=None,
        ),
    ]
