# Generated by Django 4.1.5 on 2023-06-27 14:11

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_banner_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionescentrodocumental',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='secciones'),
        ),
    ]
