# Generated by Django 4.1.5 on 2023-06-28 14:04

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_banner_banner_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eniot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePDF', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_url', models.FileField(blank=True, storage=back.models.S3Storage(), upload_to='eniot', verbose_name='Documento')),
                ('seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('anio', models.IntegerField(null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EniotAlbun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlbun', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_url', models.FileField(blank=True, storage=back.models.S3Storage(), upload_to='eniot', verbose_name='Documento')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('num_descargas', models.IntegerField(blank=True, default=0, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(storage=back.models.S3Storage(), upload_to='oteg'),
        ),
    ]
