# Generated by Django 4.1.5 on 2023-05-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_modelogd_tipo_de_visitante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otros_anuales',
        ),
    ]
