# Generated by Django 4.1.5 on 2023-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_catalogo_categorias_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('municipio', models.CharField(max_length=555)),
                ('calidad_del_aire', models.CharField(max_length=2255)),
            ],
            options={
                'verbose_name': 'aire',
                'verbose_name_plural': 'aire',
                'db_table': 'aire',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioHoteleroEntNac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=255)),
                ('habitaciones', models.IntegerField()),
                ('establecimientos', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inventario_hotelero_ent_nac',
                'verbose_name_plural': 'inventario_hotelero_ent_nac',
                'db_table': 'inventario_hotelero_ent_nac',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelTable(
            name='inventariohotelero',
            table=None,
        ),
    ]
