# Generated by Django 4.1.5 on 2023-04-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_calidadaire_inventariohoteleroentnac_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventariohotelero',
            table='inventario_hotelero_gto',
        ),
    ]
