# Generated by Django 4.1.5 on 2023-06-27 16:08

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_seccionescentrodocumental_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='url',
            field=models.FileField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='publications', verbose_name='Archivo'),
        ),
    ]
