# Generated by Django 4.1.5 on 2023-06-28 14:33

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_eniot_eniotalbun_alter_evento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=back.models.S3Storage(), upload_to='eniot', verbose_name='Imagen')),
            ],
        ),
        migrations.RemoveField(
            model_name='eniotalbun',
            name='foto_url',
        ),
        migrations.RemoveField(
            model_name='eniotalbun',
            name='num_descargas',
        ),
        migrations.AddField(
            model_name='eniotalbun',
            name='fotos',
            field=models.ManyToManyField(related_name='albunes', to='back.foto'),
        ),
    ]
