# Generated by Django 4.1.5 on 2023-03-19 19:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_glosario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
