# Generated by Django 4.1.5 on 2023-05-24 12:27

import back.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_delete_otros_anuales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTour',
        ),
        migrations.DeleteModel(
            name='GastoDerrama',
        ),
        migrations.AlterField(
            model_name='publications',
            name='url',
            field=models.FileField(blank=True, null=True, storage=back.models.S3Storage(), upload_to='publicacion', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
