# Generated by Django 4.1.5 on 2023-06-28 14:56

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_foto_remove_eniotalbun_foto_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eniotalbun',
            name='fotos',
        ),
        migrations.AddField(
            model_name='eniotalbun',
            name='foto_url',
            field=models.FileField(blank=True, storage=back.models.S3Storage(), upload_to='eniot', verbose_name='Documento'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
