# Generated by Django 4.1.5 on 2023-04-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_calidadaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalidadAire',
        ),
        migrations.DeleteModel(
            name='InventarioHotelero',
        ),
        migrations.DeleteModel(
            name='InventarioHoteleroEntNac',
        ),
        migrations.DeleteModel(
            name='InversionPublica',
        ),
    ]
