# Generated by Django 4.1.5 on 2023-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_noticia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nombre_categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='publicacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
