# Generated by Django 4.1.5 on 2023-06-27 16:25

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_publications_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='url',
        ),
        migrations.AddField(
            model_name='publications',
            name='doc',
            field=models.FileField(blank=True, storage=back.models.S3Storage(), upload_to='publications', verbose_name='Documento'),
        ),
    ]
