# Generated by Django 4.1.5 on 2023-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_delete_datatour_delete_gastoderrama_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificacion',
        ),
        migrations.DeleteModel(
            name='empleo',
        ),
        migrations.DeleteModel(
            name='inversion_privada',
        ),
        migrations.DeleteModel(
            name='Sesibilizacion',
        ),
        migrations.RemoveField(
            model_name='placesofinterest',
            name='decription',
        ),
        migrations.AddField(
            model_name='placesofinterest',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
