# Generated by Django 4.1.5 on 2023-06-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_report_report_section_delete_certificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
