# Generated by Django 4.1.5 on 2023-04-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_alter_categorias_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={},
        ),
        migrations.RemoveField(
            model_name='publications',
            name='download',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='fiel',
        ),
        migrations.AddField(
            model_name='publications',
            name='num_descargas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.categorias'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.seccionescentrodocumental'),
        ),
        migrations.AlterModelTable(
            name='publications',
            table=None,
        ),
    ]
