# Generated by Django 4.1.5 on 2023-06-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_remove_publications_url_publications_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='recent',
        ),
    ]
