# Generated by Django 4.1.5 on 2023-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_delete_calidadaire_delete_inventariohotelero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
