# Generated by Django 4.1.5 on 2023-06-30 02:47

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_remove_categorias_publicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes_Mensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, max_length=100)),
                ('ano', models.CharField(blank=True, max_length=100)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('doc', models.FileField(blank=True, storage=back.models.S3Storage(), upload_to='reportes_mensuales', verbose_name='Documento')),
            ],
        ),
    ]
