# Generated by Django 4.1.5 on 2023-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_alter_publications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='type',
            field=models.CharField(choices=[('1', 'PDF'), ('2', 'MP3'), ('3', 'XLS')], max_length=10),
        ),
    ]
