# Generated by Django 4.1.5 on 2023-06-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_delete_certificacion_delete_empleo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='report',
            name='ods1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ods9',
            field=models.BooleanField(default=False),
        ),
    ]
