# Generated by Django 4.1.5 on 2023-04-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_alter_publications_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='datatour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('cuartos_registrados', models.IntegerField()),
                ('cuartos_disponibles', models.IntegerField()),
                ('cuartos_disponibles_prom', models.IntegerField()),
                ('cuartos_ocupados', models.IntegerField()),
                ('cuartos_ocupados_residentes', models.IntegerField()),
                ('cuartos_ocupados_no_residentes', models.IntegerField()),
                ('llegadas_turistas', models.IntegerField()),
                ('llegadas_turistas_residentes', models.IntegerField()),
                ('llegadas_turistas_no_residentes', models.IntegerField()),
                ('turistas_noche', models.IntegerField()),
                ('turistas_noche_residentes', models.IntegerField()),
                ('turistas_noche_no_residentes', models.IntegerField()),
                ('porcentaje_ocupacion', models.FloatField()),
                ('porcentaje_ocupacion_residentes', models.FloatField()),
                ('porcentaje_ocupacion_no_residentes', models.FloatField()),
                ('estadia_promedio', models.FloatField()),
                ('estadia_promedio_residentes', models.FloatField()),
                ('estadia_promedio_no_residentes', models.FloatField()),
                ('densidad_ocupacion', models.FloatField()),
                ('densidad_ocupacion_residentes', models.FloatField()),
                ('densidad_ocupacion_no_residentes', models.FloatField()),
                ('fecha_recuperacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
