# Generated by Django 4.1.5 on 2023-06-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_reportes_mensuales'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes_mensuales',
            name='num_descargas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
