# Generated by Django 4.1.5 on 2023-04-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_inventariohotelero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventarioHotelero',
        ),
    ]
