# Generated by Django 4.1.5 on 2023-06-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_delete_certificacion_delete_empleo_and_more'),
    ]

    operations = [
        
        migrations.RenameField(
            model_name='report',
            old_name='section',
            new_name='dimensio',
        ),
        migrations.AddField(
            model_name='report',
            name='nomenclatura',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
