# Generated by Django 4.1.5 on 2023-04-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_datatour'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTourUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GastoDerrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('categoria', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('gasto_diario_promedio', models.FloatField()),
                ('participacion', models.FloatField()),
                ('estadia_promedio', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='datatour',
            name='fecha_recuperacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
