# Generated by Django 4.1.5 on 2023-06-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_delete_certificacion_delete_empleo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='dimensio',
            new_name='dimension',
        ),
    ]
