# Generated by Django 4.1.5 on 2023-04-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_datatourunique_gastoderrama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoderrama',
            old_name='año',
            new_name='anio',
        ),
    ]
