# Generated by Django 4.1.5 on 2023-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_delete_inventariohotelero'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioHoteleroEntNac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=255)),
                ('habitaciones', models.IntegerField()),
                ('establecimientos', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inventario_hotelero_ent_nac',
                'verbose_name_plural': 'inventario_hotelero_ent_nac',
                'db_table': 'inventario_hotelero_ent_nac',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InversionPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('municipio', models.CharField(max_length=255)),
                ('nombre_obra', models.CharField(max_length=255)),
                ('monto_inversion_municipal', models.FloatField()),
                ('monto_inversion_estatal', models.FloatField()),
                ('monto_inversion_federal', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Inversiones Públicas',
                'db_table': 'inversion_publica',
                'ordering': ['-id'],
            },
        ),
    ]
