# Generated by Django 4.1.5 on 2023-04-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_catalogo_categorias_catalogo_destinos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='otros_anuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('pib_total_sector_72', models.FloatField()),
                ('pib_total_de_actividades_terciarias', models.FloatField()),
                ('basura_generada_por_persona_diaria', models.FloatField()),
            ],
        ),
    ]
