# Generated by Django 4.1.5 on 2023-04-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_otros_anuales'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo_zonaz_arq_museos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_visitante', models.CharField(max_length=455)),
                ('tipo', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='zonas_arqueologicas_museos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('museo_zona_arqueologica', models.CharField(max_length=455)),
                ('fecha', models.DateField()),
                ('origen_visitante', models.CharField(max_length=455)),
                ('visitantes', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=455, null=True)),
            ],
        ),
    ]
