# Generated by Django 4.1.5 on 2023-04-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_catalogo_zonaz_arq_museos_zonas_arqueologicas_museos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo_zonaz_arq_museos',
            old_name='origen_visitante',
            new_name='museo_zona_arqueologica',
        ),
    ]
