# Generated by Django 4.1.5 on 2023-04-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_calidadaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalidadAire',
        ),
    ]
