# Generated by Django 4.1.5 on 2023-04-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    database = 'ecosistema'  # Especifica la base de datos a utilizar

    dependencies = [
        ('back', '0017_delete_calidadaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('municipio', models.CharField(max_length=555)),
                ('calidad_del_aire', models.CharField(max_length=2255)),
            ],
            options={
                'verbose_name': 'aire',
                'verbose_name_plural': 'aire',
                'db_table': 'aire',
                'ordering': ['-id'],
            },
        ),
    ]
