# Generated by Django 4.1.5 on 2023-04-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_calidadaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioHotelero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=255)),
                ('habitaciones', models.IntegerField()),
                ('establecimientos', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inventario_hotelero_gto',
                'verbose_name_plural': 'inventario_hotelero_gto',
                'db_table': 'inventario_hotelero_gto',
                'ordering': ['-id'],
            },
        ),
    ]
