# Generated by Django 4.1.5 on 2023-04-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_inventariohotelero'),
    ]

    operations = [
    ]
