# Generated by Django 4.1.5 on 2023-04-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_delete_calidadaire'),
    ]

    operations = [
    ]
