# Generated by Django 4.1.5 on 2023-02-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100, verbose_name='Sección')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('publication', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('recent', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('download', models.CharField(max_length=100, verbose_name='Descarga')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fiel', models.FileField(blank=True, null=True, upload_to='archivo/%y/%m/%d')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
