# Generated by Django 4.1.5 on 2023-02-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_placesofinyerest_alter_publications_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacesOfInyerest',
        ),
    ]
