# Generated by Django 4.1.5 on 2023-02-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0002_rename_bio_profile_expereincia_profile_boletin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
