# Generated by Django 4.1.5 on 2023-02-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0003_profile_apellido_materno'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
