# Generated by Django 4.1.5 on 2023-02-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0004_profile_apellido_paterno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='licencitura',
            new_name='licenciatura',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='universidad_licencitura',
            new_name='universidad_licenciatura',
        ),
    ]
