# Generated by Django 4.1.5 on 2023-02-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionescentrodocumental',
            name='categoria',
        ),
        migrations.AddField(
            model_name='seccionescentrodocumental',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='otros.categorias'),
        ),
    ]
