# Generated by Django 4.1.5 on 2023-02-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otros', '0002_remove_seccionescentrodocumental_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionescentrodocumental',
            name='categoria',
        ),
        migrations.AddField(
            model_name='seccionescentrodocumental',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='secciones_centro_documental', to='otros.categorias'),
        ),
    ]
