# Generated by Django 4.1.5 on 2023-02-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otros', '0003_remove_seccionescentrodocumental_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionescentrodocumental',
            name='categorias',
        ),
        migrations.AddField(
            model_name='categorias',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otros.seccionescentrodocumental'),
        ),
    ]
